#!/bin/bash

**** Install Haproxy ****
apt update && apt install gpg -y && export PATH=$PATH:$(which gpg)

curl https://haproxy.debian.net/bernat.debian.org.gpg \
      | gpg --dearmor > /usr/share/keyrings/haproxy.debian.net.gpg

echo deb "[signed-by=/usr/share/keyrings/haproxy.debian.net.gpg]" \
      http://haproxy.debian.net bullseye-backports-2.8 main \
      > /etc/apt/sources.list.d/haproxy.list

apt update && apt install -y  haproxy=2.8.\*

export PATH=$PATH:/usr/sbin/haproxy
sudo sysctl net.bridge.bridge-nf-call-iptables=1
echo $(sudo haproxy)


sudo systemctl enable haproxy
